alias dka='conda activate dark_knight'
alias obsse='python -m storm.engines.order_book_snapshot_engine'
alias obse='python -m storm.engines.order_book_syncing_engine'
alias ose='python -m storm.engines.order_streaming_engine'
alias afe='python -m storm.engines.arbitrage_finding_engine'